language: python
python:
    - "3.6"
install:
    - pip install pymysql
    - pip install nltk
    - pip install numpy
    - pip install scipy
    - pip install pandas
    - pip install scikit-learn
script: 
    - python -c "import nltk; nltk.download('punkt'); nltk.download('averaged_perceptron_tagger'); nltk.download('stopwords')"
    - python setup.py build
    - python setup.py install